[project]
name = "GnuCash-Dashboard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "streamlit>=1.52.1",
    "sqlalchemy>=2.0.0",
    "psycopg[binary,pool]>=3.1.0",
    "dotenv>=0.9.9",
    "psycopg2>=2.9.11",
]
